### PR TITLE
PLAT-301 Feature/heavy refactor

### PR DESCRIPTION
**Pull request by vgarvardt**
**DO NOT MERGE AS CI ENVIRONMENT IS NOT READY YET**

PR introduces heavy refactoring of the project. Application architecture did not change at all - read messages from RabbitMQ, use local memory cache, try publish to Kafka, store to Redis if publishing failed for some reason, read from Redis and try to publish again. But the internal code structure changed almost completely to meet the same coding principals as other our golang projects. Refactoring also introduces several improvements:

* Reconnect to RabbitMQ automatically if the connection is lost, e.g. when RabbitMQ restarts
* Collect application stats with [hellofresh/stats-go](https://github.com/hellofresh/stats-go)
* Load application config settings from environment variables (pipes config is loaded from file still)
* CI pipeline is similar to [janus](https://github.com/hellofresh/janus)
* Inject version to application in compile time - there is a catch here, as we create final release from last RC w/out any modification I replaced "rc.X" postfix with short hash, so the application version becomes something like **0.4.0-bcaab84**. You can get it with `./kandalf -h`.

Automation PR https://github.com/hellofresh/automation/pull/1115

As this PR is huge already I postponed several features that I want to implement before the next final release:

* Use https://github.com/spf13/viper for config loading
* Implement (return) reload to restart all services w/out restarting application
* Write more tests

### CODE REVIEW

**Comment by endeveit** [comment]
Two things:
1. I cannot see any reason for moving from the config file to env variables.
2. and I would prefer to keep deb-package

I mean, you can add support for env variables and docker, but the project itself have to be compliant with generally accepted open source projects standards.
That means: installation with package manager, working with `init.d` or `systemd`, send logs to `syslog` or store them in `/var/log`

**Comment by italolelis** [comment]
@endeveit 

1. The use of env vars makes a lot of sense, way better than having a config file (This is totally compliant with the 12 factor apps). In my opinion, I think it should be optional, using viper for example, you can choose if you wanna use yaml, json, tom or env vars.

2. Logs should always go to `stdout` or `stderr`, this way the agents (like filebeat or others) can choose if they want to stream it to a file or straight to a processor. The application should never care about where the log will be shipped to.

3. About maintaining the deb package, I don't really care here, so whatever you guys agree it's fine.

**Comment by endeveit** [comment]
@italolelis you have one major problem in your arguments.
Kandalf is not another Hellofresh internal service, built to run on our infrastructure, it is a standalone open-source utility not tied to any company and as abstract as it is possible.
Think about it as about nginx or MySQL.
That is why 12-factor apps rules are not acceptable here.

**Comment by kieranajp** [comment]
I don't see how that makes a difference?

We don't care how nginx is built internally, it could be 12-factor compliant or not.

Postgres, as an example, takes values from its environment for configuration.

**Comment by endeveit** [comment]
@kieranajp that is my point as well.
Kandalf initially was built as a plain old-school linux service and not as a 12-factor app.
I cannot find any reason to do a huge refactoring of working app, just to make it `12-factor-app-compatible`.
As I mentioned in my first comment, I'm not against environment variables, I'm against of benefitless work. If you need environment variables feel free to add support of them, but don't remove support of config files.

**Comment by vgarvardt** [comment]
Returned possibility to load settings from YAML config file, but changed its structure a bit.

Added deb artefact generation (not tested yet).

Added first tests for loading config.

**Comment by kieranajp** [comment]
So "if it ain't broke don't fix it"? 😉 

Though I agree it's nice to have the option.

**Comment by endeveit** [comment]
@kieranajp it depends on what you're talking about 🙂
If you're pushing for changes just to make kandalf `12-factor-apps`-compatible, I definitely against it.
Because this project has other nature and it was initially built in a different way.

**Comment by kieranajp** [comment]
I'm with you on that, but matching the code structure to other go projects is a big win as it reduces cognitive load drastically.

**Comment by italolelis** [comment]
@endeveit 12 factor apps are a big thing, doesn't matter what is the nature of it. Ngxin, MySQL, and Postgres are good examples of it. 
Again, I believe that it should be optional, if you wanna use Env vars or yml or smth else do it, do not be restrict by not being flexible, on this point I agree with you.

Since this will be maintained by our tribe I think it should comply with our defined standards and how we build `go` applications.

**Comment by endeveit** [comment]
@italolelis, I'm not against environment variables as a config and I'm not against `12-factor-apps` in general.
I'm just saying that kandalf initially was designed in a different way and since it is open-sourced, you have to keep BC and not to couple it to HelloFresh's infrastructure just because since this app was written and went live, we've got new standards how be build `go` apps in HelloFresh.

**Comment by vgarvardt** [comment]
@endeveit about keeping BC - app has version 0.3.x that means, in general, that every minor release may introduce BC breakers. I bumped version to 0.4 for the next RC/release. But anyway I agree that it is nice to have both ways to configure application and it is already implemented.

I'm still debugging CI to build both binaries and deb for GH release, but the application code will not be changed a lot.

**Comment by italolelis** [comment]
👍

**Pull request merged**
